export const rows = [
  {
    key: "",
    name: "",
    status: "",
    website: "",
  },
  {
    key: "2",
    name: "Suzy Ahn",
    status: "University of Ottawa, Assistant Professor",
    website: "https://sites.google.com/view/suzyahn",
  },
  {
    key: "3",
    name: "Adam Albright",
    status: "MIT Professor",
    website: "https://linguistics.mit.edu/user/albright/",
  },
  {
    key: "4",
    name: "Ann Aly",
    status: "TechFlow Inc., Director of Human Centered Design",
    website: "Vacation",
  },
  {
    key: "5",
    name: "Victoria Anderson",
    status: "University of Hawai`i at Manoa, Associate Professor",
    website: "http://www2.hawaii.edu/~vanderso/",
  },
  {
    key: "6",
    name: "Steve Anderson",
    status: "Retired From Yale Dept. of Linguistics",
    website: "https://cowgill.ling.yale.edu/sra/",
  },
  {
    key: "7",
    name: "Alice Anderton",
    status: "",
    website: "",
  },
  {
    key: "8",
    name: "Norma Antonanzas",
    status: "UCLA Bureau of Glottal Affairs",
    website: "",
  },
  {
    key: "9",
    name: "Tim Arbisi-Kelm",
    status:
      "Boys Town National Research Hospital Word Learning Laboratory, Research Staff",
    website:
      "https://www.boystownhospital.org/research/faculty/timothy-arbisi-kelm",
  },
  {
    key: "10",
    name: "Vernon Austel",
    status: "IBM's T.J. Watson Research Center",
    website: "",
  },
  {
    key: "11",
    name: "Heriberto Avelino",
    status: "Professor, I.N. de Antropologia e Historia, Mexico",
    website:
      "https://s3.amazonaws.com/files.pucp.edu.pe/posgrado/mes-internacional/2019/08/21152003/avelino_cv.pdf",
  },
  {
    key: "12",
    name: "Mary Baltazani",
    status: "University of Oxford, Departmental Lecturer",
    website: "https://oxford.academia.edu/MaryBaltazani",
  },
  {
    key: "13",
    name: "Marco Baroni",
    status:
      "Catalan Institution for Research & Advanced Studies (ICREA), Research Professor",
    website: "http://clic.cimec.unitn.it/marco/",
  },
  {
    key: "14",
    name: "Roy Becker-Kristal",
    status:
      "Prosody Specialist at Speech Morphing; Phonetics Specialist at Voiceitt",
    website:
      "https://www.linkedin.com/in/roy-becker-kristal-71696634/?originalSubdomain=il",
  },
  {
    key: "15",
    name: "Roger Billerey-Mosier",
    status: "Virta Health, Director, security & CISO",
    website: "https://www.linkedin.com/in/rogerbm/",
  },
  {
    key: "16",
    name: "Jason Bishop",
    status: "City University of New York, Associate Professor",
    website: "https://jbishop.ws.gc.cuny.edu/",
  },
  {
    key: "17",
    name: "Barbara Blankenship",
    status: "Professor at UCLA",
    website: "https://linguistics.ucla.edu/people/blankenship/",
  },
  {
    key: "18",
    name: "Dustin Bowers",
    status: "University of Arizona, Visiting Scholar",
    website: "",
  },
  {
    key: "19",
    name: "Canaan M. Breiss",
    status: "Assistant Professor, USC Linguistics (2023)",
    website: "https://www.cbreiss.com/",
  },
  {
    key: "20",
    name: "Cathe Browman",
    status: "",
    website: "http://www.haskins.yale.edu/browman.html",
  },
  {
    key: "21",
    name: "Nadia Brunetti",
    status: "",
    website: "",
  },
  {
    key: "22",
    name: "Roslyn Burns",
    status: "Lecturer at Yale",
    website: "http://www.linguisticking.com/about.html",
  },
  {
    key: "23",
    name: "Dani Byrd",
    status:
      "Linguistics Profesor, Dornsife College of Letters, Arts and Sciences, University of Southern California",
    website: "https://sites.google.com/view/danibyrd-home?pli=1",
  },
  {
    key: "24",
    name: "Andrew Bye",
    status: "OpenText, Strategy Consultant",
    website: "https://www.linkedin.com/in/andrew-bye-7607503/",
  },
  {
    key: "25",
    name: "Lorena Cayré Baito",
    status: "",
    website: "",
  },
  {
    key: "26",
    name: "Yuan Chai",
    status: "University of Washington, Seattle",
    website: "https://yuanchaiyc.github.io/website/",
  },
  {
    key: "27",
    name: "Marjorie Chan (陳潔雯)",
    status: "Ohio State University, Associate Professor",
    website: "https://deall.osu.edu/people/chan.9",
  },
  {
    key: "28",
    name: "Taehong Cho",
    status: "Professor of Linguistics (HYU Distinguished Research Fellow)",
    website: "https://tcho.hanyang.ac.kr/home",
  },
  {
    key: "29",
    name: "John Choi",
    status: "",
    website: "",
  },
  {
    key: "30",
    name: "Adam Chong",
    status:
      "Senior Lecturer in Linguistics, Director - QMUL Phonetics Lab, Queen Mary University of London",
    website: "https://www.adamjchong.com/",
  },
  {
    key: "31",
    name: "Abby Cohn",
    status: "Professor at Cornell",
    website: "",
  },
  {
    key: "32",
    name: "Court Crowther",
    status: "Assistant Dean at UC Irvine",
    website: "https://grad.uci.edu/about-us/contact-us.php",
  },
  {
    key: "33",
    name: "Robert Daland",
    status:
      "Software Engineer at Apple, Siri's Natural Language Understanding team",
    website: "https://scholar.google.com/citations?user=hN7N19QAAAAJ&amp;hl=en",
  },
  {
    key: "34",
    name: "Sarah Dart",
    status: "",
    website: "",
  },
  {
    key: "35",
    name: "Deborah Davison",
    status: "",
    website: "",
  },
  {
    key: "36",
    name: "Sandy Disner",
    status: "Professor at USC",
    website: "http://www.linguistic-expert.com/",
  },
  {
    key: "37",
    name: "Bill Dolan",
    status: "Microsoft, Partner Research Manager",
    website:
      "https://www.microsoft.com/en-us/research/people/billdol/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fpeople%2Fbilldol%2F",
  },
  {
    key: "38",
    name: "Beatriz Amos Dukes",
    status: "",
    website: "",
  },
  {
    key: "39",
    name: "Ken de Jong",
    status: "Indiana University, Professor of Linguistics & Cognitive Science",
    website: "https://cl.indiana.edu/~kdejong/",
  },
  {
    key: "40",
    name: "Karen Emmorey",
    status: "Professor of Speech Language at SDSU",
    website: "https://slhs.sdsu.edu/people/karen-emmorey/",
  },
  {
    key: "41",
    name: "Melissa Epstein",
    status: "Albert Einstein College of Medicine, IRB Director",
    website:
      "https://www.einstein.yu.edu/administration/institutional-review-board/staff-list.aspx",
  },
  {
    key: "42",
    name: "Christina Esposito",
    status: "Associate Professor and Chair of Linguistics, Macalester College",
    website:
      "https://www.macalester.edu/linguistics/facultystaff/christinaesposito/",
  },
  {
    key: "43",
    name: "Matt Faytak",
    status: "Postdoctoral Fellow at UCLA",
    website: "https://mfaytak.github.io/",
  },
  {
    key: "44",
    name: "Heidi Heidi Macbride (Fleischhacker)",
    status: "Software Engineer (Data) at Factual",
    website: "https://www.linkedin.com/in/heidi-macbride-8b863426/",
  },
  {
    key: "45",
    name: "Edward Flemming",
    status: "Associate Professor of Linguistics at MIT",
    website: "http://linguistics.mit.edu/user/flemming/",
  },
  {
    key: "46",
    name: "James Forrest Fordyce",
    status: "lendale Community College, English as a Second Language",
    website: "",
  },
  {
    key: "47",
    name: "Christina Foreman",
    status: "Speech Pathologist in Hartford, CT",
    website: "",
  },
  {
    key: "48",
    name: "Vicki Fromkin",
    status: "",
    website: "",
  },
  {
    key: "49",
    name: "Cecile Fougeron",
    status:
      "CNRS-Université Sorbonne-Nouvelle, Senior Scientist & Laboratoire de Phonétique et Phonologie",
    website: "",
  },
  {
    key: "50",
    name: "Sean Fulop",
    status: "Professor of Linguistics at Fresno State",
    website: "https://seanfulop.weebly.com/",
  },
  {
    key: "51",
    name: "Jack Gandour",
    status:
      "Department of Speech Language Hearing Sciences at Purdue University",
    website: "https://web.ics.purdue.edu/~gandour/",
  },
  {
    key: "52",
    name: "Marc Garellek",
    status: "Professor of Linguistics at UC San Diego",
    website: "https://pages.ucsd.edu/~mgarellek/",
  },
  {
    key: "53",
    name: "Eleanor Glewwe",
    status: "Visiting Assistant Professor at Grinnell College",
    website: "https://eglewwe.com/",
  },
  {
    key: "54",
    name: "Manuel Godinez, Jr.",
    status: "",
    website: "",
  },
  {
    key: "55",
    name: "Louis Goldstein",
    status: "Professor of Linguistics at USC",
    website:
      "https://dornsife.usc.edu/cf/ling/ling_faculty_display.cfm?Person_ID=1016450",
  },
  {
    key: "56",
    name: "Matt Gordon",
    status: "Professor of Linguistics at UC Santa Barbara",
    website: "http://www.linguistics.ucsb.edu/faculty/gordon/",
  },
  {
    key: "57",
    name: "Steve Greenberg",
    status: "",
    website: "",
  },
  {
    key: "58",
    name: "Narineh Hacopian",
    status: "",
    website: "",
  },
  {
    key: "59",
    name: "Rob Hagiwara",
    status: "Assistant Professor of Linguistics at the University of Manitoba",
    website: "http://home.cc.umanitoba.ca/~robh/",
  },
  {
    key: "60",
    name: "Caroline Henton",
    status: "Phonetician, Speech Technologist, Talknowledgy",
    website: "https://www.linkedin.com/in/caroline-henton-b35118/",
  },
  {
    key: "61",
    name: "Susan Hess",
    status: "",
    website: "",
  },
  {
    key: "62",
    name: "Jean-Marie Hombert",
    status: "CNRS, Director of Research",
    website:
      "http://www.ddl.ish-lyon.cnrs.fr/Annuaires/Index.asp?Langue=FR&Page=Jean-Marie%20HOMBERT",
  },
  {
    key: "63",
    name: "Damir Horga",
    status: "University of Zagreb, Croatia, Phonetics Department",
    website:
      "https://www-gewi.uni-graz.at/gralis-alt/4.Gralisarium/GraLiS%202004/Horga_Zagr.%20Phonetic.htm",
  },
  {
    key: "64",
    name: "Chai-Shune Hsu",
    status: "Formerly at Nuance",
    website: "",
  },
  {
    key: "65",
    name: "Marie Huffman",
    status: "Associate Professor at Stony Brook University",
    website: "https://linguistics.stonybrook.edu/faculty/marie.huffman/",
  },
  {
    key: "66",
    name: "Sue Banner Inouye",
    status: "Professor at the University of Hawaii Kapiolani Community College",
    website: "https://www.linkedin.com/in/susan-banner-inouye-3a0a8035/",
  },
  {
    key: "67",
    name: "Michel T.-T. Jackson",
    status:
      "Sensimetrics Corporation, Principal Research Scientist & Programmer",
    website: "https://www.linkedin.com/in/michel-jackson-4b8b867",
  },
  {
    key: "68",
    name: "L. Carl Jacobsen (formerly Leon C. Jacobsen)",
    status: "",
    website: "",
  },
  {
    key: "69",
    name: "Rachel Jacobson",
    status: "",
    website: "",
  },
  {
    key: "70",
    name: "Hector Javkin",
    status: "Researcher on Assistive Speech Technology",
    website:
      "https://www.researchgate.net/scientific-contributions/Hector-Javkin-70784618",
  },
  {
    key: "71",
    name: "Amanda Jones",
    status: "Professional Services Group, Associate Director",
    website: "https://www.h5.com/team/amanda-jones/",
  },
  {
    key: "72",
    name: "Keith Johnson",
    status: "Director of Phonetics & Phonology Lab at UC Berkeley",
    website: "http://linguistics.berkeley.edu/~kjohnson/",
  },
  {
    key: "73",
    name: "Allard Jongman",
    status: "Professor of Phonetics at the University of Kansas",
    website: "https://linguistics.ku.edu/people/allard-jongman",
  },
  {
    key: "74",
    name: "Hiro Katsuda",
    status: "Postdoctoral Researcher at the University of Toronto Scarborough",
    website: "https://www.utsc.utoronto.ca/dls/hironori-katsuda",
  },
  {
    key: "75",
    name: "Sameer Khan",
    status: "Associate Professor at Reed College",
    website: "https://www.reed.edu/linguistics/khan/",
  },
  {
    key: "76",
    name: "Yun Jung Kim",
    status:
      "Director of Undergraduate Research at the Emory College of Arts & Sciences",
    website: "http://linguistics.emory.edu/home/people/corefaculty/kim.html",
  },
  {
    key: "77",
    name: "Sahyang Kim",
    status: "Professor at Hongik University, Department of English Education",
    website: "https://sahyangkim.weebly.com/index.html",
  },
  {
    key: "78",
    name: "Robert Kirchner",
    status: "Edmonton, Alberta, Retired",
    website: "https://c4ss.org/content/author/robert-kirchner",
  },
  {
    key: "79",
    name: "Chin-Woo Kim",
    status: "Professor Emeritus at the University of Illinois",
    website: "http://www.linguistics.illinois.edu/people/cwkim",
  },
  {
    key: "80",
    name: "Paul Kirk",
    status: "CSUN, Emeritus",
    website: "",
  },
  {
    key: "81",
    name: "Jody Kreiman",
    status: "Professor of Head & Neck Surgery & Linguistics at UCLA",
    website: "https://www.uclahealth.org/head-neck-surgery/bga/people#kreiman",
  },
  {
    key: "82",
    name: "Jianjing Kuang",
    status:
      "Associate Professor of Linguistics at the University of Pennsylvania",
    website: "https://www.sas.upenn.edu/~kuangj/Home.html",
  },
  {
    key: "83",
    name: "Grace Kuo",
    status:
      "National Taiwan University, Assistant Professor in the Department of Foreign Languages & Literatures",
    website: "",
  },
  {
    key: "84",
    name: "Jennifer Kuo",
    status: "Assistant Professor at Cornell University",
    website: "https://www.kuojennifer.com/",
  },
  {
    key: "85",
    name: "Jenny Ladefoged",
    status: "",
    website: "",
  },
  {
    key: "86",
    name: "Peter Ladefoged",
    status: "",
    website: "https://linguistics.ucla.edu/people/ladefoge/",
  },
  {
    key: "87",
    name: "Jose Maria Lahoz",
    status: "Profesor Ayudante Doctor at the Universidad Complutense Madrid",
    website:
      "https://www.ucm.e/lengespyteoliter/cv-lahoz-bengoechea-jose-maria",
  },
  {
    key: "88",
    name: "Eun Hwa Lee",
    status: "",
    website: "",
  },
  {
    key: "89",
    name: "Hyuck-Joon Lee",
    status: "",
    website: "",
  },
  {
    key: "90",
    name: "Tatiana Libman",
    status: "",
    website: "",
  },
  {
    key: "91",
    name: "Isabelle Lin",
    status: "",
    website: "",
  },
  {
    key: "92",
    name: "Ying Lin",
    status: "",
    website: "",
  },
  {
    key: "93",
    name: "Mona Lindau",
    status: "",
    website: "http://www.bestdogtrainer.net/",
  },
  {
    key: "94",
    name: "Wendy Linker",
    status: "",
    website: "",
  },
  {
    key: "95",
    name: "Xiao Liu",
    status: "",
    website: "",
  },
  {
    key: "96",
    name: "Ingvar Lofstedt",
    status: "",
    website: "",
  },
  {
    key: "97",
    name: "Ian Maddieson",
    status:
      "Adjunct Research Professor at the University of New Mexico & Professor Emeritus at UC Berkeley",
    website: "http://www.unm.edu/~ianm/",
  },
  {
    key: "98",
    name: "Peggy MacEachern",
    status: "",
    website: "",
  },
  {
    key: "99",
    name: "Andy Martin",
    status: "Konan University, Kobe, Japan",
    website: "https://www.konan-u.ac.jp/english/academics/letters/english.html",
  },
  {
    key: "100",
    name: "Connor Mayer",
    status:
      "Assistant Professor, Department of Language Science at The University of California, Irvine",
    website: "http://socsci.uci.edu/~cjmayer/",
  },
  {
    key: "101",
    name: "Joyce McDonough",
    status: "Professor of Linguistics at the University of Massachusetts",
    website: "http://www.sas.rochester.edu/lin/people/faculty/mcdonough_joyce/",
  },
  {
    key: "102",
    name: "Benjamin Munson",
    status:
      "Professor in the Department of Speech-Language-Hearing Sciences at the University of Minnesota",
    website: "https://cla.umn.edu/about/directory/profile/munso005",
  },
  {
    key: "103",
    name: "Laura (Dolly) Meyers",
    status: "",
    website: "",
  },
  {
    key: "104",
    name: "Jonas Nartey (or Akpanglo-Nartey)",
    status: "",
    website: "",
  },
  {
    key: "105",
    name: "Kuniko Yasu Nielsen",
    status: "Associate Professor of Linguistics at Oakland University",
    website: "https://files.oakland.edu/users/nielsen/web/",
  },
  {
    key: "106",
    name: "Mira Oh",
    status: "",
    website: "",
  },
  {
    key: "107",
    name: "John Ohala",
    status: "Emeritus Professor of Linguistics at UC Berkeley, Deceased 2020",
    website: "http://linguistics.berkeley.edu/~ohala/",
  },
  {
    key: "108",
    name: "Ho-hsien Pan",
    status: "National Chiao Tung University",
    website:
      "https://www.researchgate.net/scientific-contributions/Ho-Hsien-Pan-15617440",
  },
  {
    key: "109",
    name: "George Papcun",
    status: "",
    website: "http://soundevidence.com/",
  },
  {
    key: "110",
    name: "Christine Prechtel",
    status: "",
    website: "https://www.linkedin.com/in/christine-prechtel/",
  },
  {
    key: "111",
    name: "Kristin Precoda",
    status: "SRI's Speech Technology & Research Laboratory",
    website:
      "http://www.speech.sri.com/https://www.sri.com/about/organization/information-computing-sciences/star-laboratory",
  },
  {
    key: "112",
    name: "Ren Hong-mo",
    status: "",
    website: "",
  },
  {
    key: "113",
    name: "Lloyd Rice",
    status: "patent review editor for JASA",
    website: "http://asa.aip.org/jasa.html",
  },
  {
    key: "114",
    name: "Meg Risdal",
    status: "Kaggle, Product Manager",
    website: "https://www.kaggle.com/mrisdal",
  },
  {
    key: "115",
    name: "Brice Roberts",
    status: "Analyst at Accenture",
    website: "",
  },
  {
    key: "116",
    name: "J'aime Roemer",
    status: "",
    website: "",
  },
  {
    key: "117",
    name: "Adam Royer",
    status: "",
    website: "",
  },
  {
    key: "118",
    name: "Bonny Sands",
    status: "Professor at Northern Arizona University",
    website: "https://www.researchgate.net/profile/Bonny-Sands",
  },
  {
    key: "119",
    name: "Rebecca Brown Scarborough",
    status:
      "Associate Professor & Associate Chair for Graduate Studies at the University of Colorado",
    website: "https://spot.colorado.edu/~scarborr/",
  },
  {
    key: "120",
    name: "Amy Schafer",
    status: "Professor of Linguistics at University of Hawaii at Manoa",
    website: "http://www2.hawaii.edu/~aschafer/",
  },
  {
    key: "121",
    name: "Mary Lee Scott",
    status: "",
    website: "",
  },
  {
    key: "122",
    name: "Adrienne Scutellaro",
    status: "",
    website: "",
  },
  {
    key: "123",
    name: "Joan Sereno",
    status: "Professor of Psycholinguistics at the University of Kansas",
    website: "https://linguistics.ku.edu/joan-sereno",
  },
  {
    key: "124",
    name: "Michael Shalev",
    status: "",
    website: "",
  },
  {
    key: "125",
    name: "Molly Shilman",
    status: "",
    website: "",
  },
  {
    key: "126",
    name: "Caroline Sigouin",
    status: "",
    website: "https://www.mendeley.com/profiles/caroline-sigouin/",
  },
  {
    key: "127",
    name: "Dan Silverman",
    status: "",
    website: "https://seedyroad.com/",
  },
  {
    key: "128",
    name: "Caroline Smith",
    status: "Professor of Linguistics at the University of New Mexico",
    website: "http://ling.unm.edu/about/people/faculty/caroline-smith.html",
  },
  {
    key: "129",
    name: "Tim Smith",
    status: "",
    website: "",
  },
  {
    key: "130",
    name: "Aaron Shryock",
    status: "",
    website: "",
  },
  {
    key: "131",
    name: "Jeremy Steffman",
    status: "Postdoctoral Fellow at Northwestern University",
    website: "https://jsteffman.github.io/",
  },
  {
    key: "132",
    name: "Donca Steriade",
    status: "Professor of Linguistics MIT",
    website: "https://linguistics.mit.edu/user/steriade/",
  },
  {
    key: "133",
    name: "Beth Sturman",
    status: "Growth Strategist, thrv",
    website: "https://bsturman.humspace.ucla.edu/",
  },
  {
    key: "134",
    name: "Sumiko Takayanagi",
    status: "UCLA School of Nursing",
    website: "https://www.nursing.ucla.edu/",
  },
  {
    key: "135",
    name: "Cheng Cheng Saw Tan",
    status: "",
    website: "",
  },
  {
    key: "136",
    name: "Yu Tanaka",
    status:
      "Doshisha University, Assistant Profesor in the Faculty of Culture & Information Science",
    website: "",
  },
  {
    key: "137",
    name: "Katie Schack Tang",
    status: "",
    website: "",
  },
  {
    key: "138",
    name: "Henry Tehrani",
    status: "Retired",
    website: "",
  },
  {
    key: "139",
    name: "Dale R. Terbeek",
    status: "",
    website: "",
  },
  {
    key: "140",
    name: "Victoria Thatte",
    status: "",
    website: "",
  },
  {
    key: "141",
    name: "Kimberly Thomas (Thomas-Vilakati)",
    status: "San Bernardino City Unified School District",
    website: "",
  },
  {
    key: "142",
    name: "Siri Tuttle",
    status: "",
    website: "",
  },
  {
    key: "143",
    name: "Yuichi Todaka",
    status: "Miyazaki Municipal University",
    website: "",
  },
  {
    key: "144",
    name: "Motoko Ueyama",
    status: "Associate Professor in the Department of Interpretation & Translation at Università Di Bologna",
    website: "",
  },
  {
    key: "145",
    name: "Martina Urbani",
    status: "",
    website: "",
  },
  {
    key: "146",
    name: "Diana Van Lancker Sidtis",
    status: "",
    website: "https://steinhardt.nyu.edu/faculty_bios/view/Diana_Van_Lancker_Sidtis",
  },
  {
    key: "147",
    name: "Ralph Vanderslice",
    status: "",
    website: "",
  },
  {
    key: "148",
    name: "Lauren Varner",
    status: "",
    website: "",
  },
  {
    key: "149",
    name: "Chad Vicenik",
    status: "",
    website: "",
  },
  {
    key: "150",
    name: "Caiyu Wang",
    status: "",
    website: "",
  },
  {
    key: "151",
    name: "Nancy Ward",
    status: "",
    website: "",
  },
  {
    key: "152",
    name: "Harry Whitaker",
    status: "Northern Michigan University, Department of Psychological Science, Retired",
    website: "https://www.researchgate.net/profile/Harry-Whitaker",
  },
  {
    key: "153",
    name: "James White",
    status: "University College London, Associate Professor of Linguistics",
    website: "https://www.ucl.ac.uk/~ucjtcwh/",
  },
  {
    key: "154",
    name: "Colin Wilson",
    status: "Johns Hopkins, Professor & Interim Chair of Cognitive Science",
    website: "https://cogsci.jhu.edu/directory/colin-wilson/",
  },
  {
    key: "155",
    name: "Anne Wingate",
    status: "",
    website: "",
  },
  {
    key: "156",
    name: "Andreas Wittenstein",
    status: "BitJazz Inc., Chief Technology Officer",
    website: "http://www.bitjazz.com/en/company/executive_profiles.php",
  },
  {
    key: "157",
    name: "Richard Wright",
    status: "University of Washington, Department of Linguistics, Professor and Department Chair",
    website: "https://linguistics.washington.edu/people/richard-wright",
  },
  {
    key: "158",
    name: "Meng Yang",
    status: "UCLA Linguistics",
    website: "",
  },
  {
    key: "159",
    name: "Kristine Yu",
    status: "University of Massachusetts Amherst, Associate Professor of Linguistics",
    website: "https://www.krisyu.org/",
  },
  {
    key: "160",
    name: "Eric Zee",
    status: "The Chinese University of Hong Kong, Language Aquisition Lab",
    website: "http://www.arts.cuhk.edu.hk/~lal/people.html#ericzee",
  },
  {
    key: "161",
    name: "Jie Zhang",
    status: "Kansas University, Professor, Department Chair Phonology",
    website: "https://linguistics.ku.edu/jie-zhang",
  },
  {
    key: "162",
    name: "Jesse Zymet",
    status: "Lecturer in Phonology at UC Berkeley",
    website: "http://linguistics.berkeley.edu/~jzymet/",
  },
];

export const columns = [
  {
    key: "name",
    label: "NAME",
  },
  {
    key: "status",
    label: "STATUS",
  },
  {
    key: "website",
    label: "WEBSITE",
  },
];
